from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time
import pytest

@pytest.fixture()
def test_open():
    options = Options()
    options.add_argument('--headless')
    browser = webdriver.Chrome(options=options)
    browser.get("https://www.tsum.ru/")
    time.sleep(3)
    men = browser.find_element(By.XPATH, '//a[@data-test-id="menCatalog"]')
    men.click()
    time.sleep(3)
    shoes = browser.find_element(By.LINK_TEXT, "Обувь")
    shoes.click()
    time.sleep(3)
    brand = browser.find_element(By.XPATH, '//span[@class="Pane__text___DQdGd"]')
    brand.click()
    time.sleep(3)
    brand0 = browser.find_element(By.XPATH, '//input[@data-test-id="brandSearchInput"]')
    brand0.click()
    brand0.send_keys("Off")
    time.sleep(3)
    brand1 = browser.find_element(By.XPATH, '//span[@class="Checkbox__control___I7Vtg"]')
    brand1.click()
    time.sleep(3)
    brand2 = browser.find_element(By.XPATH, '//button[@class="Button__button___TK6mu BrandFilter__counterButton___fuBhQ Button__primary___iIgS3 Button__stretch___w_KVD"]')
    brand2.click()
    time.sleep(3)
    shoes1 = browser.find_element(By.XPATH, '//img[@alt="Off-White"]')
    shoes1.click()
    time.sleep(3)
    size = browser.find_element(By.XPATH, '//span[text()="40"]')
    size.click()
    time.sleep(3)
    putcart = browser.find_element(By.XPATH, '//button[@class="Button__button___eIaLo Button__primary___sDC89 Button__medium___yUqaA Button__withoutIcon___uRcTi Controls__buttons___R_FsB Controls__filled___F1IG2 Controls__buttons__cart___xuKjj"]')
    putcart.click()
    time.sleep(3)
    cart = browser.find_element(By.XPATH, '//li[@data-test-id="cartButton"]')
    cart.click()
    time.sleep(6)
    buy = browser.find_element(By.XPATH, '//span[text()="Купить выбранный товар"]')
    buy.click()
    time.sleep(6)
    delivery1 = browser.find_element(By.XPATH, '//input[1]')
    delivery1.send_keys("г Санкт-Петербург, ул Ультрамариновая, д 3 стр 1")
    time.sleep(3)
    delivery2 = browser.find_element(By.XPATH, '//p[@class="Text__title___ovskQ"]')
    delivery2.click()
    time.sleep(3)
    numb1 = browser.find_element(By.XPATH, '//input[@name="tel"]')
    numb1.click()
    time.sleep(6)
    numb1.send_keys("9932503028")
    lastandname = browser.find_element(By.XPATH, '//input[@placeholder="Имя и Фамилия"]')
    lastandname.click()
    lastandname.send_keys("Джеймс Адамсон")
    time.sleep(3)
    card1 = browser.find_element(By.XPATH, '//b[text()="Банковская карта"]')
    card1.click()
    time.sleep(6)
    buy = browser.find_element(By.XPATH, '//button[@class="Button__button___eIaLo Button__primary___sDC89 Button__large___dAlVx Button__orange___h0Mfp Button__withoutIcon___uRcTi Button__fullWidth___aCeRi ConfirmationButton__btn___Qbxsb ConfirmationButton__online___yISnL"]')
    buy.click()
    time.sleep(3)
    browser.quit()