from selenium import webdriver
from selenium.webdriver.common.by import By
import time

browser = webdriver.Chrome()

def test_open():
 browser.get("http://testingchallenges.thetestingmap.org/")
 time.sleep(3)
 pole = browser.find_element(By.XPATH, '//input[@name="firstname"]')
 pole.click()
 pole.send_keys(" ")
 submit = browser.find_element(By.XPATH, '//input[@name="formSubmit"]')
 submit.click()
 time.sleep(3)
 pole = browser.find_element(By.XPATH, '//input[@name="firstname"]')
 pole.click()
 pole.send_keys("t")
 submit = browser.find_element(By.XPATH, '//input[@name="formSubmit"]')
 submit.click()
 time.sleep(3)
 pole = browser.find_element(By.XPATH, '//input[@name="firstname"]')
 pole.click()
 pole.send_keys("test")
 submit = browser.find_element(By.XPATH, '//input[@name="formSubmit"]')
 submit.click()
 time.sleep(3)
 pole = browser.find_element(By.XPATH, '//input[@name="firstname"]')
 pole.click()
 pole.send_keys("testtesttesttesttesttesttesttesttesttest")
 submit = browser.find_element(By.XPATH, '//input[@name="formSubmit"]')
 submit.click()
 time.sleep(3)
 pole = browser.find_element(By.XPATH, '//input[@name="firstname"]')
 pole.click()
 pole.send_keys("")
 submit = browser.find_element(By.XPATH, '//input[@name="formSubmit"]')
 submit.click()
 time.sleep(3)
 pole = browser.find_element(By.XPATH, '//input[@name="firstname"]')
 pole.click()
 pole.send_keys(" 'sql injection' ")
 submit = browser.find_element(By.XPATH, '//input[@name="formSubmit"]')
 submit.click()
 time.sleep(3)
 pole = browser.find_element(By.XPATH, '//input[@name="firstname"]')
 pole.click()
 pole.send_keys("<script>alert(228)</script>")
 submit = browser.find_element(By.XPATH, '//input[@name="formSubmit"]')
 submit.click()
 time.sleep(3)
 pole = browser.find_element(By.XPATH, '//input[@name="firstname"]')
 pole.click()
 pole.send_keys("dfjwGGe82H43g3uRiy53h")
 submit = browser.find_element(By.XPATH, '//input[@name="formSubmit"]')
 submit.click()
 time.sleep(3)
 pole = browser.find_element(By.XPATH, '//input[@name="firstname"]')
 pole.click()
 pole.send_keys("oi32jnxd42390slk345")
 submit = browser.find_element(By.XPATH, '//input[@name="formSubmit"]')
 submit.click()
 otvet15 = browser.find_element(By.CLASS_NAME, 'values-tested')
 print(otvet15.text)
 time.sleep(3)